[package]
name = "link_checker"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
lazy_static = "1"

config = { path = "../config" }
errors = { path = "../errors" }
