[package]
name = "zola"
version = "0.10.0"
authors = ["Vincent Prouillet <hello@vincentprouillet.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
description = "A fast static site generator with everything built-in"
homepage = "https://www.getzola.org"
repository = "https://github.com/getzola/zola"
keywords = ["static", "site", "generator", "blog"]
# build = "build.rs"

[build-dependencies]
clap = "2"

[[bin]]
name = "zola"

[features]
default = ["request", "serve"]
request = ["rebuild/request", "site/request"]
serve = [
    "hyper",
    "hyper-staticfile",
    "tokio",
    "notify",
    "ws",
    "ctrlc",
    "open",
    "globset",
]

[dependencies]
atty = "0.2.11"
clap = "2"
chrono = "0.4"
lazy_static = "1.1.0"
termcolor = "1.0.4"
# Used in init to ensure the url given as base_url is a valid one
url = "2"
# Below is for the serve cmd
hyper = { version = "0.13", default-features = false, features = ["runtime"], optional = true }
hyper-staticfile = { version = "0.5", optional = true }
tokio = { version = "0.2", default-features = false, features = [], optional = true }
notify = { version = "4", optional = true }
ws = { version = "0.9", optional = true }
ctrlc = { version = "3", optional = true }
open = { version = "1.2", optional = true }
globset = { version = "0.4", optional = true }

site = { path = "components/site", default-features = false }
errors = { path = "components/errors" }
front_matter = { path = "components/front_matter" }
utils = { path = "components/utils" }
rebuild = { path = "components/rebuild", default-features = false }

[workspace]
members = [
    "components/config",
    "components/errors",
    "components/front_matter",
    "components/rebuild",
    "components/rendering",
    "components/site",
    "components/templates",
    "components/utils",
    "components/search",
    "components/imageproc",
    "components/link_checker",
    "components/library",
]

[profile.release]
lto = true
codegen-units = 1
