[package]
name = "site"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[features]
default = ["request"]
request = ["link_checker", "library/request", "search/request", "templates/request"]

[dependencies]
tera = "1"
glob = "0.3"
rayon = "1"
serde = "1"
serde_derive = "1"
sass-rs = "0.2"

errors = { path = "../errors" }
config = { path = "../config" }
utils = { path = "../utils" }
templates = { path = "../templates", default-features = false }
front_matter = { path = "../front_matter" }
search = { path = "../search", default-features = false }
imageproc = { path = "../imageproc" }
library = { path = "../library", default-features = false }
link_checker = { path = "../link_checker", optional = true }

[dev-dependencies]
tempfile = "3"
