[package]
name = "search"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[dependencies]
elasticlunr-rs = "2"
ammonia = "3"
lazy_static = "1"

errors = { path = "../errors" }
library = { path = "../library" }
