base_url = "https://www.getzola.org/"
title = "Zola"
description = "Everything you need to make a static site engine in one binary."

compile_sass = true
highlight_code = true
insert_anchor_links = true
highlight_theme = "kronuz"
build_search_index = true

[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = [
    "http://127.0.0.1",
]

# Skip anchor checking for external URLs that start with these prefixes
# skip_anchor_prefixes = [
#     "https://caniuse.com/",
# ]

[extra]
author = "Vincent Prouillet"
