name: gutenberg # you probably want to 'snapcraft register <name>'
version: '0.3.3+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: A fast static site generator in a single binary with everything built-in.
description: |
  A fast static site generator in a single binary with everything built-in.
  https://www.getgutenberg.io

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  gutenberg:
    command: gutenberg
    plugs:
      - network
      - network-bind

parts:
  gutenberg:
    plugin: x-rust
    rust-channel: stable
    build-packages:
    - build-essential
    - cmake
    - git-core
