[package]
name = "templates"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[features]
default = ["request"]
request = ["reqwest", "url", "library/request"]

[dependencies]
tera = "1"
base64 = "0.11"
lazy_static = "1"
pulldown-cmark = "0.6"
toml = "0.5"
csv = "1"
image = "0.22"
serde_json = "1.0"
reqwest = { version = "0.10", features = ["blocking"], optional = true }
url = { version = "2", optional = true }

errors = { path = "../errors" }
utils = { path = "../utils" }
library = { path = "../library", default-features = false }
config = { path = "../config" }
imageproc = { path = "../imageproc" }

[dev-dependencies]
mockito = "0.22"
