[package]
name = "templates"
# Version must match that of root Cargo.toml
version = "0.5.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]

[dependencies]
tera = "0.11"
base64 = "0.9"
lazy_static = "1"
pulldown-cmark = "0"
toml = "0.4"
csv = "1"
serde_json = "1.0"
error-chain = "0.12"
crypto-hash = "0.3.1"
chrono = "0.4"
reqwest = "0.9"
url = "1.5"
clap = "2"

errors = { path = "../errors" }
utils = { path = "../utils" }
library = { path = "../library" }
config = { path = "../config" }
imageproc = { path = "../imageproc" }
