[package]
name = "imageproc"
version = "0.1.0"
authors = ["Vojtěch Král <vojtech@kral.hk>"]

[dependencies]
lazy_static = "1"
regex = "1.0"
tera = "0.11.0"
image = "0.19.0"
rayon = "0.9"

errors = { path = "../errors" }
utils = { path = "../utils" }
