[package]
name = "imageproc"
version = "0.1.0"
authors = ["Vojtěch Král <vojtech@kral.hk>"]

[dependencies]
lazy_static = "1"
regex = "1.0"
tera = "1.0.0-beta.17"
image = "0.22"
rayon = "1"

errors = { path = "../errors" }
utils = { path = "../utils" }
